### ISSUE TITLE
Documentation Optimization

### ISSUE THREAD

**Issue by surajpheudin** [DipendraPaudel/date-picker-np#1]
I was confused about the minimum and maximum date values.

![date-picker-np-npm-11-26-2024_05_28_PM](https://github.com/user-attachments/assets/841646f5-f71b-4b5b-b88a-4f30cb91da1b)

Can we write date values in the Nepali language or add BS at the end?

**Comment by DipendraPaudel** [comment]
documentation has been updated and will be pushed in next update
