### ISSUE TITLE
not able to use the component

### ISSUE THREAD

**Issue by Kuldip-Bhutoria** [DipendraPaudel/date-picker-np#3]
tried to run your basic example. got this error

 ⨯ node_modules\date-picker-np\dist\index.umd.js (1:255) @ eval
 ⨯ ReferenceError: document is not defined

**Comment by DipendraPaudel** [comment]
could you explain more ?
What version are you using and are you using nextjs?

**Comment by DipendraPaudel** [comment]
I've identified the issue, which occurs only in Next.js, while it works fine in React, and I'm currently working on a solution.

**Comment by DipendraPaudel** [comment]
@Kuldip-Bhutoria the issue has been resolved in latest release
try using the version 1.0.15
