### ISSUE TITLE
Scrolling not working in year selection.

### ISSUE THREAD

**Issue by Kuldip-Bhutoria** [DipendraPaudel/date-picker-np#4]
when you scroll down on the year select menu, it takes you through various pages but this fails sometimes and scroll doesnt work.

**Comment by DipendraPaudel** [comment]
normal scrolling has been added instead of that
and will push that in the upcoming version (1.0.16) when ready and tested

**Comment by DipendraPaudel** [comment]
@Kuldip-Bhutoria new scrolling feature has been added and pushed in 1.0.17
